Repository boostcampwm-2024/refactor-web30-stop-troublepainter, pull requests merged in 2025-01, with the labels that each got.

#3 chore: Add Prometheus metrics endpoint for server monitoring
  nginx.conf
  pnpm-lock.yaml
  server/package.json
  server/src/app.module.ts
  server/src/metrics/metrics.controller.ts
  server/src/metrics/metrics.module.ts
Labels: 💻 BE, ⚙ Setting

#8 refactor: Optimize Largest Contentful Paint
  client/index.html
  client/src/assets/background-tiny.png
  client/src/components/ui/BackgroundImage.tsx
  client/src/components/ui/Button.tsx
  client/src/components/ui/HelpContainer.tsx
  client/src/components/ui/Loading.tsx
  client/src/components/ui/Logo.tsx
  client/src/constants/cdn.ts
  client/src/hooks/useBackgroundMusic.ts
  client/src/index.css
  client/src/layouts/GameLayout.tsx
  client/src/main.tsx
  client/src/pages/MainPage.tsx
  client/src/routes.tsx
Labels: 💻 FE, 📈 Improvement

#16 fix: Update Redis key format and improve Socket error handling
  server/src/chat/chat.gateway.ts
  server/src/chat/chat.repository.ts
  server/src/drawing/drawing.gateway.ts
  server/src/drawing/drawing.repository.ts
  server/src/game/game.gateway.ts
Labels: 💻 BE, 🐞 BugFix

#22 feat: Add Redis Adapter configuration
  pnpm-lock.yaml
  server/package.json
  server/src/adapters/redis-io.adapter.ts
  server/src/main.ts
Labels: 💻 BE, 🔨 Refactor

#13 feat: Enhance drawing with Bezier curve interpolation
  client/src/hooks/canvas/useDrawing.ts
  client/src/hooks/canvas/useDrawingOperation.ts
  client/src/routes.tsx
Labels: 💻 FE, 📈 Improvement
