Repository boostcampwm-2024/refactor-web30-stop-troublepainter, pull requests merged in 2025-02, with the labels that each got.

#26 feat: Implement drawing verification with OpenAI
  .github/workflows/client-ci-cd.yml
  .github/workflows/server-ci-cd.yml
  docker-compose.yml
  pnpm-lock.yaml
  server/package.json
  server/src/common/services/openai/openai.module.ts
  server/src/common/services/openai/openai.service.ts
  server/src/common/types/game.types.ts
  server/src/game/game.gateway.ts
  server/src/game/game.module.ts
  server/src/game/game.repository.ts
  server/src/game/game.service.ts
Labels: 💻 BE, 📈 Improvement

#17 refactor: Refactor HelpModal
  .gitignore
  client/package.json
  client/src/assets/lottie/game-win.lottie
  client/src/assets/lottie/help/fifth.json
  client/src/assets/lottie/help/fifth.lottie
  client/src/assets/lottie/help/first.json
  client/src/assets/lottie/help/first.lottie
  client/src/assets/lottie/help/fourth.json
  client/src/assets/lottie/help/fourth.lottie
  client/src/assets/lottie/help/second.json
  client/src/assets/lottie/help/second.lottie
  client/src/assets/lottie/help/third.json
  client/src/assets/lottie/help/third.lottie
  client/src/components/canvas/CanvasToolbar.tsx
  client/src/components/canvas/DrawingArea.tsx
  client/src/components/canvas/MainCanvas.tsx
  client/src/components/modal/HelpRollingModal.tsx
  client/src/components/ui/HelpPage.tsx
  client/src/types/help.types.ts
  client/vite.config.ts
  pnpm-lock.yaml
Labels: 💻 FE, 🔨 Refactor, 📈 Improvement

#18 test: Add Lighthouse performance tests using Playwright
  .github/workflows/lighthouse-ci-cd.yml
  .gitignore
  client/package.json
  client/playwright.config.ts
  client/src/tests/lighthouse/lighthouse.config.ts
  client/src/tests/lighthouse/lighthouse.test.ts
  client/src/tests/lighthouse/lighthouse.type.ts
  client/src/tests/lighthouse/lighthouse.util.ts
  client/tsconfig.app.json
  pnpm-lock.yaml
Labels: 💻 FE, ✅ Test

#28 fix: Update checkDrawing method to use dynamic room answers
  server/src/game/game.gateway.ts
  server/src/game/game.service.ts
Labels: 💻 BE, 🐞 BugFix

#31 refactor: Update image handling with NCP Object Storage integration
  .github/workflows/client-ci-cd.yml
  .github/workflows/server-ci-cd.yml
  docker-compose.yml
  pnpm-lock.yaml
  server/package.json
  server/src/common/services/openai/openai.service.ts
  server/src/game/game.gateway.ts
  server/src/game/game.service.ts
Labels: 💻 BE, 🔨 Refactor

#37 refactor: Implement custom keyword AI generation to server and client
  client/src/components/room-setting/Setting.tsx
  client/src/components/room-setting/SettingContent.tsx
  client/src/components/room-setting/SettingItem.tsx
  client/src/components/room-setting/WordsThemeModalContent.tsx
  client/src/hooks/useBackgroundMusic.ts
  client/src/pages/LobbyPage.tsx
  client/src/utils/soundManager.ts
  core/types/game.types.ts
  server/src/common/services/openai/openai.service.ts
  server/src/common/types/game.types.ts
  server/src/game/game.repository.ts
  server/src/game/game.service.ts
Labels: 📬 API, 💻 BE, 💻 FE, 🎨 HTML&CSS, 📈 Improvement

#39 feat: Implement Korean profanity filter for words theme
  client/src/components/room-setting/Setting.tsx
  client/src/components/room-setting/WordsThemeModalContent.tsx
  client/src/constants/wordsThemeValidation.ts
  client/src/types/wordsTheme.types.ts
  client/src/utils/wordsThemeValidation.ts
  package.json
  pnpm-lock.yaml
Labels: 💻 FE, 📈 Improvement

#41 refactor: Convert canvas image to WebP format to optimize server traffic
  client/src/components/canvas/GameCanvas.tsx
  client/src/hooks/canvas/useDrawingOperation.ts
  client/src/utils/checkWebPSupport.ts
  client/src/utils/getCanvasUint8Array.ts
Labels: 💻 FE, 🔨 Refactor
